export enum EAvailableLanguage {
  EN = "en",
  UK = "uk",
}

export enum EEndpoints {
  AUTH = "/auth",
}

export enum EModalKey {
  LOGIN = "LOGIN",
  SING_UP = "SING_UP",
  CREATE_MEDKIT = "CREATE_MEDKIT",
  CREATE_MEDICINE = "CREATE_MEDICINE",
  CONFIRM_DIALOG = "CONFIRM_DIALOG",
  IDENTIFY_PILLS = "IDENTIFY_PILLS",
  EDIT_IDENTIFIED_PILLS = "EDIT_IDENTIFIED_PILLS",
  MANAGE_MEDKIT_MEMBERS = "MANAGE_MEDKIT_MEMBERS",
}

export enum EQueryKey {
  PROFILE = "PROFILE",
  MEDKITS = "MEDKITS",
  MEDKIT = "MEDKIT",
  MEDICINES = "MEDICINES",
  NOTIFICATIONS = "NOTIFICATIONS",
  AI_RECOMMENDATIONS = "AI_RECOMMENDATIONS",
}

export enum ETableName {
  MEDKITS = "MEDKITS",
  MEDICINES = "MEDICINES",
  NOTIFICATIONS = "NOTIFICATIONS",
}
