import { IMedicines } from "@/shared/types/entities";

const generateDate = (daysFromNow: number) => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date;
};

const generateTimestamp = (daysAgo: number) => {
  const date = new Date();
  date.setDate(date.getDate() - daysAgo);
  return {
    createdAt: date,
    updatedAt: date,
  };
};

export const MEDICINES_MOCK: IMedicines[] = [
  {
    id: "1",
    name: "Paracetamol 500mg",
    activeIngredient: "Paracetamol",
    description: "Препарат для зниження температури та зняття болю",
    usageInstructions:
      "Приймати по 1-2 таблетки 3-4 рази на день після їжі. Максимальна добова доза - 4г",
    sideEffects: "Рідко: алергічні реакції, висипання на шкірі",
    contraindications:
      "Підвищена чутливість до парацетамолу, важкі порушення функції печінки",
    storageConditions:
      "Зберігати в сухому місці при температурі до 25°C, недоступному для дітей",
    quantity: 20,
    medkitId: "1",
    expiryDate: generateDate(365),
    ts: generateTimestamp(30),
  },
  {
    id: "2",
    name: "Ibuprofen 400mg",
    activeIngredient: "Ibuprofen",
    description:
      "Нестероїдний протизапальний препарат для зняття болю та запалення",
    usageInstructions: "Приймати по 1 таблетці 3 рази на день після їжі",
    sideEffects: "Можливі: нудота, біль у животі, запаморочення",
    contraindications:
      "Виразкова хвороба, важкі порушення функції нирок, вагітність",
    storageConditions:
      "Зберігати в оригінальній упаковці при температурі до 25°C",
    quantity: 15,
    medkitId: "1",
    expiryDate: generateDate(180),
    ts: generateTimestamp(45),
  },
  {
    id: "3",
    name: "Амоксицилін 500mg",
    activeIngredient: "Amoxicillin",
    description:
      "Антибіотик широкого спектру дії для лікування бактеріальних інфекцій",
    usageInstructions:
      "Приймати по 1 капсулі 3 рази на день за 1 годину до або через 2 години після їжі",
    sideEffects: "Діарея, нудота, алергічні реакції",
    contraindications: "Підвищена чутливість до пеніцилінів",
    storageConditions: "Зберігати в сухому місці при температурі до 25°C",
    quantity: 21,
    medkitId: "1",
    expiryDate: generateDate(730),
    ts: generateTimestamp(60),
  },
  {
    id: "4",
    name: "Аспірин 100mg",
    activeIngredient: "Acetylsalicylic acid",
    description: "Антиагрегант для профілактики серцево-судинних захворювань",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день після їжі",
    sideEffects: "Шлунково-кишкові порушення, підвищена схильність до кровотеч",
    contraindications: "Виразкова хвороба, гемофілія, вагітність",
    storageConditions: "Зберігати в сухому, прохолодному місці",
    quantity: 30,
    medkitId: "1",
    expiryDate: generateDate(540),
    ts: generateTimestamp(20),
  },
  {
    id: "5",
    name: "Омепразол 20mg",
    activeIngredient: "Omeprazole",
    description: "Інгібітор протонної помпи для лікування виразкової хвороби",
    usageInstructions:
      "Приймати по 1 капсулі вранці натщесерце за 30 хвилин до їжі",
    sideEffects: "Головний біль, діарея, біль у животі",
    contraindications: "Підвищена чутливість до омепразолу",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 28,
    medkitId: "1",
    expiryDate: generateDate(450),
    ts: generateTimestamp(75),
  },
  {
    id: "6",
    name: "Лоратадин 10mg",
    activeIngredient: "Loratadine",
    description: "Антигістамінний препарат для лікування алергічних реакцій",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день",
    sideEffects: "Сонливість, сухість у роті (рідко)",
    contraindications: "Підвищена чутливість до лоратадину",
    storageConditions: "Зберігати в сухому місці при температурі до 25°C",
    quantity: 10,
    medkitId: "1",
    expiryDate: generateDate(300),
    ts: generateTimestamp(90),
  },
  {
    id: "7",
    name: "Цитрамон",
    activeIngredient: "Paracetamol, Caffeine, Acetylsalicylic acid",
    description: "Комбінований препарат для зняття головного болю",
    usageInstructions:
      "Приймати по 1-2 таблетки при болю, але не частіше ніж кожні 4 години",
    sideEffects: "Шлунково-кишкові порушення при тривалому прийомі",
    contraindications: "Виразкова хвороба, порушення функції печінки",
    storageConditions: "Зберігати в сухому місці",
    quantity: 20,
    medkitId: "1",
    expiryDate: generateDate(200),
    ts: generateTimestamp(15),
  },
  {
    id: "8",
    name: "Но-шпа 40mg",
    activeIngredient: "Drotaverine",
    description: "Спазмолітик для зняття спазмів гладкої мускулатури",
    usageInstructions: "Приймати по 1-2 таблетки 2-3 рази на день",
    sideEffects: "Рідко: запаморочення, прискорення серцебиття",
    contraindications: "Важка серцева недостатність, підвищена чутливість",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 24,
    medkitId: "1",
    expiryDate: generateDate(400),
    ts: generateTimestamp(50),
  },
  {
    id: "9",
    name: "Активирований вугіль",
    activeIngredient: "Activated charcoal",
    description: "Ентеросорбент для зняття інтоксикації та отруєння",
    usageInstructions:
      "Приймати по 4-8 таблеток 3-4 рази на день, розжовуючи або розтираючи",
    sideEffects: "Запор, чорне забарвлення калу",
    contraindications:
      "Виразкова хвороба, кровотечі з шлунково-кишкового тракту",
    storageConditions: "Зберігати в сухому місці",
    quantity: 50,
    medkitId: "1",
    expiryDate: generateDate(1095),
    ts: generateTimestamp(100),
  },
  {
    id: "10",
    name: "Вітамін D3 2000 МО",
    activeIngredient: "Cholecalciferol",
    description: "Вітамін для підтримки імунітету та здоров'я кісток",
    usageInstructions: "Приймати по 1 капсулі 1 раз на день під час їжі",
    sideEffects: "При передозуванні: гіперкальціємія",
    contraindications: "Гіперкальціємія, гіперкальціурія",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 60,
    medkitId: "1",
    expiryDate: generateDate(730),
    ts: generateTimestamp(25),
  },
  {
    id: "11",
    name: "Амброксол 30mg",
    activeIngredient: "Ambroxol",
    description: "Муколітичний препарат для лікування кашлю з важкою мокротою",
    usageInstructions: "Приймати по 1 таблетці 3 рази на день після їжі",
    sideEffects: "Шлунково-кишкові порушення, алергічні реакції",
    contraindications: "Виразкова хвороба, підвищена чутливість",
    storageConditions: "Зберігати в сухому місці",
    quantity: 20,
    medkitId: "1",
    expiryDate: generateDate(250),
    ts: generateTimestamp(35),
  },
  {
    id: "12",
    name: "Німесулід 100mg",
    activeIngredient: "Nimesulide",
    description: "Нестероїдний протизапальний препарат для зняття болю",
    usageInstructions: "Приймати по 1 таблетці 2 рази на день після їжі",
    sideEffects: "Шлунково-кишкові порушення, головний біль",
    contraindications: "Виразкова хвороба, важкі порушення функції печінки",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 20,
    medkitId: "1",
    expiryDate: generateDate(180),
    ts: generateTimestamp(40),
  },
  {
    id: "13",
    name: "Фурацилін",
    activeIngredient: "Nitrofural",
    description: "Антисептик для зовнішнього застосування",
    usageInstructions:
      "Розчинити 1 таблетку в 100мл води, використовувати для полоскання",
    sideEffects: "Алергічні реакції при місцевому застосуванні",
    contraindications: "Підвищена чутливість до нітрофурану",
    storageConditions: "Зберігати в сухому місці",
    quantity: 10,
    medkitId: "1",
    expiryDate: generateDate(600),
    ts: generateTimestamp(55),
  },
  {
    id: "14",
    name: "Лінекс",
    activeIngredient: "Lactobacillus, Bifidobacterium, Enterococcus",
    description: "Пробіотик для нормалізації мікрофлори кишечника",
    usageInstructions: "Приймати по 2 капсули 3 рази на день після їжі",
    sideEffects: "Рідко: алергічні реакції",
    contraindications: "Підвищена чутливість до компонентів",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 32,
    medkitId: "1",
    expiryDate: generateDate(365),
    ts: generateTimestamp(65),
  },
  {
    id: "15",
    name: "Смекта",
    activeIngredient: "Diosmectite",
    description: "Антацидний та адсорбуючий препарат для лікування діареї",
    usageInstructions:
      "Розчинити водержання 1 пакетика в 100мл води, приймати 3 рази на день",
    sideEffects: "Запор (рідко)",
    contraindications: "Кишкова непрохідність",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 10,
    medkitId: "1",
    expiryDate: generateDate(450),
    ts: generateTimestamp(30),
  },
  {
    id: "16",
    name: "Ентерол 250mg",
    activeIngredient: "Saccharomyces boulardii",
    description: "Пробіотик для лікування та профілактики діареї",
    usageInstructions:
      "Приймати по 1-2 капсули 2 рази на день за 1 годину до їжі",
    sideEffects: "Метеоризм (рідко)",
    contraindications: "Підвищена чутливість до дріжджів",
    storageConditions: "Зберігати в сухому місці при температурі до 25°C",
    quantity: 20,
    medkitId: "1",
    expiryDate: generateDate(365),
    ts: generateTimestamp(80),
  },
  {
    id: "17",
    name: "Гексорал",
    activeIngredient: "Hexetidine",
    description: "Антисептик для лікування інфекцій ротової порожнини та горла",
    usageInstructions: "Полоскати рот 15мл розчину 2 рази на день",
    sideEffects: "Тимчасове зміна смаку, алергічні реакції",
    contraindications: "Підвищена чутливість до гексетидину",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 1,
    medkitId: "1",
    expiryDate: generateDate(730),
    ts: generateTimestamp(45),
  },
  {
    id: "18",
    name: "Називін",
    activeIngredient: "Oxymetazoline",
    description: "Сосудозвужувальний препарат для лікування закладеного носа",
    usageInstructions:
      "Закапувати по 1-2 краплі в кожну ніздрю 2-3 рази на день",
    sideEffects: "Сухість слизових, подразнення",
    contraindications: "Атрофічний риніт, закритокутна глаукома",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 1,
    medkitId: "1",
    expiryDate: generateDate(365),
    ts: generateTimestamp(20),
  },
  {
    id: "19",
    name: "Супрастин 25mg",
    activeIngredient: "Chloropyramine",
    description: "Антигістамінний препарат для лікування алергічних реакцій",
    usageInstructions: "Приймати по 1 таблетці 3-4 рази на день під час їжі",
    sideEffects: "Сонливість, сухість у роті",
    contraindications: "Вагітність, глаукома, аденома простати",
    storageConditions: "Зберігати в сухому місці",
    quantity: 20,
    medkitId: "1",
    expiryDate: generateDate(300),
    ts: generateTimestamp(70),
  },
  {
    id: "20",
    name: "Валеріана екстракт",
    activeIngredient: "Valerian extract",
    description: "Седативний препарат на основі рослинної сировини",
    usageInstructions: "Приймати по 1-2 таблетки 2-3 рази на день",
    sideEffects: "Сонливість, при гіпердозуванні - загальмованість",
    contraindications: "Підвищена чутливість до валеріани",
    storageConditions: "Зберігати в сухому, прохолодному місці",
    quantity: 40,
    medkitId: "1",
    expiryDate: generateDate(540),
    ts: generateTimestamp(95),
  },
  {
    id: "21",
    name: "Магній B6",
    activeIngredient: "Magnesium, Pyridoxine",
    description: "Препарат для поповнення дефіциту магнію та вітаміну B6",
    usageInstructions: "Приймати по 2 таблетки 3 рази на день під час їжі",
    sideEffects: "Діарея при передозуванні",
    contraindications: "Важка ниркова недостатність",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 50,
    medkitId: "1",
    expiryDate: generateDate(730),
    ts: generateTimestamp(85),
  },
  {
    id: "22",
    name: "Кеторол 10mg",
    activeIngredient: "Ketorolac",
    description: "Потужний знеболюючий препарат",
    usageInstructions:
      "Приймати по 1 таблетці при болю, максимум 4 рази на день",
    sideEffects: "Шлунково-кишкові порушення, головний біль",
    contraindications: "Виразкова хвороба, важкі порушення функції нирок",
    storageConditions: "Зберігати в сухому місці",
    quantity: 20,
    medkitId: "1",
    expiryDate: generateDate(200),
    ts: generateTimestamp(10),
  },
  {
    id: "23",
    name: "Цетрин 10mg",
    activeIngredient: "Cetirizine",
    description: "Антигістамінний препарат другого покоління",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день",
    sideEffects: "Сонливість (рідко), сухість у роті",
    contraindications: "Підвищена чутливість до цетризину",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 20,
    medkitId: "1",
    expiryDate: generateDate(400),
    ts: generateTimestamp(50),
  },
  {
    id: "24",
    name: "Діклофенак 50mg",
    activeIngredient: "Diclofenac",
    description:
      "Нестероїдний протизапальний препарат для зняття болю та запалення",
    usageInstructions: "Приймати по 1 таблетці 2-3 рази на день після їжі",
    sideEffects: "Шлунково-кишкові порушення, головний біль",
    contraindications: "Виразкова хвороба, важкі порушення функції печінки",
    storageConditions: "Зберігати в сухому місці",
    quantity: 30,
    medkitId: "1",
    expiryDate: generateDate(250),
    ts: generateTimestamp(60),
  },
  {
    id: "25",
    name: "Ферум Лек",
    activeIngredient: "Iron(III) hydroxide",
    description: "Препарат заліза для лікування залізодефіцитної анемії",
    usageInstructions: "Приймати по 1-2 таблетки 1-2 рази на день після їжі",
    sideEffects: "Запор, чорне забарвлення калу",
    contraindications: "Гемохроматоз, гемосидероз",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 50,
    medkitId: "1",
    expiryDate: generateDate(365),
    ts: generateTimestamp(40),
  },
  {
    id: "26",
    name: "Ацикловір 200mg",
    activeIngredient: "Acyclovir",
    description: "Противірусний препарат для лікування герпесу",
    usageInstructions: "Приймати по 1 таблетці 5 разів на день",
    sideEffects: "Нудота, головний біль, висипання",
    contraindications: "Підвищена чутливість до ацикловіру",
    storageConditions: "Зберігати в сухому місці",
    quantity: 35,
    medkitId: "2",
    expiryDate: generateDate(450),
    ts: generateTimestamp(75),
  },
  {
    id: "27",
    name: "Мукалтін",
    activeIngredient: "Althaea officinalis extract",
    description: "Відхаркувальний препарат на основі алтеї",
    usageInstructions: "Приймати по 1-2 таблетки 3 рази на день перед їжею",
    sideEffects: "Алергічні реакції (рідко)",
    contraindications: "Підвищена чутливість до алтеї",
    storageConditions: "Зберігати в сухому місці",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(540),
    ts: generateTimestamp(25),
  },
  {
    id: "28",
    name: "Біфіформ",
    activeIngredient: "Bifidobacterium, Enterococcus",
    description: "Пробіотик для нормалізації мікрофлори кишечника",
    usageInstructions: "Приймати по 2-3 капсули на день під час їжі",
    sideEffects: "Алергічні реакції (рідко)",
    contraindications: "Підвищена чутливість до компонентів",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(55),
  },
  {
    id: "29",
    name: "Флуконазол 150mg",
    activeIngredient: "Fluconazole",
    description: "Протигрибковий препарат для лікування кандидозу",
    usageInstructions: "Приймати 1 капсулу одноразово",
    sideEffects: "Головний біль, нудота, висипання",
    contraindications: "Підвищена чутливість до флуконазолу",
    storageConditions: "Зберігати в сухому місці",
    quantity: 1,
    medkitId: "2",
    expiryDate: generateDate(730),
    ts: generateTimestamp(90),
  },
  {
    id: "30",
    name: "Метформін 500mg",
    activeIngredient: "Metformin",
    description: "Препарат для лікування цукрового діабету 2 типу",
    usageInstructions:
      "Приймати по 1 таблетці 2-3 рази на день під час або після їжі",
    sideEffects: "Діарея, нудота, металевий присмак",
    contraindications: "Діабетична кома, важкі порушення функції нирок",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 60,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(30),
  },
  {
    id: "31",
    name: "Еналаприл 10mg",
    activeIngredient: "Enalapril",
    description: "Інгібітор АПФ для лікування артеріальної гіпертензії",
    usageInstructions: "Приймати по 1 таблетці 1-2 рази на день",
    sideEffects: "Кашель, головокружіння, гіпотензія",
    contraindications: "Вагітність, двосторонній стеноз ниркових артерій",
    storageConditions: "Зберігати в сухому місці",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(450),
    ts: generateTimestamp(65),
  },
  {
    id: "32",
    name: "Аторвастатин 20mg",
    activeIngredient: "Atorvastatin",
    description: "Статин для зниження рівня холестерину",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день ввечері",
    sideEffects: "Біль у м'язах, головний біль, порушення функції печінки",
    contraindications: "Важкі порушення функції печінки, вагітність",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(50),
  },
  {
    id: "33",
    name: "Амлодипін 5mg",
    activeIngredient: "Amlodipine",
    description: "Блокатор кальцієвих каналів для лікування гіпертензії",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день",
    sideEffects: "Набряки ніг, головокружіння, приливи крові",
    contraindications: "Шок, важкий аортальний стеноз",
    storageConditions: "Зберігати в сухому місці",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(400),
    ts: generateTimestamp(80),
  },
  {
    id: "34",
    name: "Бісопролол 5mg",
    activeIngredient: "Bisoprolol",
    description:
      "Бета-блокатор для лікування артеріальної гіпертензії та тахікардії",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день вранці",
    sideEffects: "Брадикардія, втома, холодні кінцівки",
    contraindications: "Серцева недостатність, бронхіальна астма",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(45),
  },
  {
    id: "35",
    name: "Лозартан 50mg",
    activeIngredient: "Losartan",
    description:
      "Блокатор рецепторів ангіотензину II для лікування гіпертензії",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день",
    sideEffects: "Запаморочення, головний біль, кашель (рідше ніж АПФ)",
    contraindications: "Вагітність, двосторонній стеноз ниркових артерій",
    storageConditions: "Зберігати в сухому місці",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(450),
    ts: generateTimestamp(70),
  },
  {
    id: "36",
    name: "Варфарин 2.5mg",
    activeIngredient: "Warfarin",
    description: "Антикоагулянт для профілактики тромбозів",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день в однаковий час",
    sideEffects: "Кровотечі, синці, гематоми",
    contraindications:
      "Вагітність, активна кровотеча, важкі порушення функції печінки",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 100,
    medkitId: "2",
    expiryDate: generateDate(730),
    ts: generateTimestamp(100),
  },
  {
    id: "37",
    name: "Клопидогрель 75mg",
    activeIngredient: "Clopidogrel",
    description: "Антиагрегант для профілактики тромбозів",
    usageInstructions: "Приймати по 1 таблетці 1 раз на день",
    sideEffects: "Кровотечі, висипання, діарея",
    contraindications: "Активна кровотеча, важкі порушення функції печінки",
    storageConditions: "Зберігати в сухому місці",
    quantity: 28,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(35),
  },
  {
    id: "38",
    name: "Преднізолон 5mg",
    activeIngredient: "Prednisolone",
    description:
      "Глюкокортикостероїд для лікування запальних та алергічних захворювань",
    usageInstructions:
      "Приймати по 1-6 таблеток на день за призначенням лікаря",
    sideEffects: "Збільшення ваги, остеопороз, підвищення тиску",
    contraindications: "Системні грибкові інфекції, вагітність",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 100,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(60),
  },
  {
    id: "39",
    name: "Левотіроксин 50мкг",
    activeIngredient: "Levothyroxine",
    description: "Гормон щитоподібної залози для лікування гіпотиреозу",
    usageInstructions:
      "Приймати по 1 таблетці вранці натщесерце за 30 хвилин до їжі",
    sideEffects: "При передозуванні: тахікардія, безсоння",
    contraindications:
      "Тиреотоксикоз, нелікована недостатність надниркових залоз",
    storageConditions: "Зберігати в сухому місці",
    quantity: 100,
    medkitId: "2",
    expiryDate: generateDate(730),
    ts: generateTimestamp(85),
  },
  {
    id: "40",
    name: "Метоклопрамід 10mg",
    activeIngredient: "Metoclopramide",
    description: "Протиблювотний препарат та стимулятор перистальтики",
    usageInstructions:
      "Приймати по 1 таблетці 3-4 рази на день за 30 хвилин до їжі",
    sideEffects: "Сонливість, екстрапірамідні розлади",
    contraindications: "Феохромоцитома, епілепсія",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(300),
    ts: generateTimestamp(40),
  },
  {
    id: "41",
    name: "Домперидон 10mg",
    activeIngredient: "Domperidone",
    description: "Протиблювотний препарат",
    usageInstructions:
      "Приймати по 1 таблетці 3-4 рази на день за 15-30 хвилин до їжі",
    sideEffects: "Сухість у роті, головний біль",
    contraindications: "Проколова виразка, кровотеча з ШКТ",
    storageConditions: "Зберігати в сухому місці",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(250),
    ts: generateTimestamp(55),
  },
  {
    id: "42",
    name: "Лактулоза 667mg/мл",
    activeIngredient: "Lactulose",
    description: "Проносний засіб для лікування запора",
    usageInstructions: "Приймати по 15-45мл 1-2 рази на день",
    sideEffects: "Метеоризм, біль у животі",
    contraindications: "Кишкова непрохідність, галактоземія",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 1,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(25),
  },
  {
    id: "43",
    name: "Бісакоділ 5mg",
    activeIngredient: "Bisacodyl",
    description: "Проносний засіб для лікування запора",
    usageInstructions: "Приймати по 1-2 таблетки ввечері перед сном",
    sideEffects: "Біль у животі, діарея",
    contraindications:
      "Кишкова непрохідність, гострі запальні захворювання кишківника",
    storageConditions: "Зберігати в сухому місці",
    quantity: 20,
    medkitId: "2",
    expiryDate: generateDate(400),
    ts: generateTimestamp(75),
  },
  {
    id: "44",
    name: "Хлорохін 250mg",
    activeIngredient: "Chloroquine",
    description: "Протималярійний та протиревматичний препарат",
    usageInstructions: "Приймати за призначенням лікаря",
    sideEffects: "Нудота, головний біль, висипання, ретинопатія",
    contraindications:
      "Вагітність, ретинопатія, важкі порушення функції печінки",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 30,
    medkitId: "2",
    expiryDate: generateDate(730),
    ts: generateTimestamp(90),
  },
  {
    id: "45",
    name: "Азитроміцин 500mg",
    activeIngredient: "Azithromycin",
    description: "Антибіотик-азолід для лікування бактеріальних інфекцій",
    usageInstructions:
      "Приймати по 1 таблетці 1 раз на день за 1 годину до або через 2 години після їжі",
    sideEffects: "Діарея, нудота, біль у животі",
    contraindications: "Підвищена чутливість до макролідів",
    storageConditions: "Зберігати в сухому місці",
    quantity: 3,
    medkitId: "2",
    expiryDate: generateDate(450),
    ts: generateTimestamp(15),
  },
  {
    id: "46",
    name: "Цефтриаксон 1g",
    activeIngredient: "Ceftriaxone",
    description: "Антибіотик цефалоспорин для ін'єкційного введення",
    usageInstructions:
      "Вводити внутрішньом'язово або внутрішньовенно за призначенням лікаря",
    sideEffects: "Алергічні реакції, діарея, флебіт",
    contraindications: "Підвищена чутливість до цефалоспоринів",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 1,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(50),
  },
  {
    id: "47",
    name: "Доксициклін 100mg",
    activeIngredient: "Doxycycline",
    description: "Антибіотик тетрациклін для лікування інфекцій",
    usageInstructions: "Приймати по 1 капсулі 2 рази на день після їжі",
    sideEffects: "Нудота, фотосенсибілізація, порушення формування зубів",
    contraindications:
      "Вагітність, діти до 8 років, важкі порушення функції печінки",
    storageConditions: "Зберігати в сухому місці",
    quantity: 20,
    medkitId: "2",
    expiryDate: generateDate(400),
    ts: generateTimestamp(65),
  },
  {
    id: "48",
    name: "Ципрофлоксацин 500mg",
    activeIngredient: "Ciprofloxacin",
    description: "Антибіотик фторхінолон для лікування інфекцій",
    usageInstructions: "Приймати по 1 таблетці 2 рази на день",
    sideEffects: "Нудота, діарея, головний біль, тендиніт",
    contraindications: "Вагітність, діти до 18 років, епілепсія",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 10,
    medkitId: "2",
    expiryDate: generateDate(365),
    ts: generateTimestamp(30),
  },
  {
    id: "49",
    name: "Метронідазол 250mg",
    activeIngredient: "Metronidazole",
    description: "Протипротозойний та антибактеріальний препарат",
    usageInstructions: "Приймати по 1 таблетці 3 рази на день після їжі",
    sideEffects: "Нудота, металевий присмак, темне забарвлення сечі",
    contraindications: "Вагітність, важкі порушення функції печінки",
    storageConditions: "Зберігати в сухому місці",
    quantity: 20,
    medkitId: "2",
    expiryDate: generateDate(450),
    ts: generateTimestamp(80),
  },
  {
    id: "50",
    name: "Римантадин 50mg",
    activeIngredient: "Rimantadine",
    description: "Противірусний препарат для профілактики та лікування грипу",
    usageInstructions: "Приймати по 1 таблетці 2 рази на день після їжі",
    sideEffects: "Нудота, головний біль, безсоння",
    contraindications: "Вагітність, важкі порушення функції печінки та нирок",
    storageConditions: "Зберігати при температурі до 25°C",
    quantity: 20,
    medkitId: "2",
    expiryDate: generateDate(300),
    ts: generateTimestamp(95),
  },
];
